function dydp=AMIGO_gen_obs_sens_MIPPE(x,dxdp,inputs,p,exp)
%function automatically generated by AMIGO_gen_obs_sens
% calculates the sensitivities of the observables from state sensitivities

% states:
Cit_mrna   =x(:,1);
Cit_foldedP=x(:,2);
Cit_fluo   =x(:,3);
Cit_AU     =x(:,4);

% parameters:
alpha1  =p(1);
Vm1     =p(2);
h1      =p(3);
Km1     =p(4);
d1      =p(5);
alpha2  =p(6);
d2      =p(7);
Kf      =p(8);
sc_molec=p(9);

switch exp
	case 1
		dydp = zeros(1,9,601);
		dhdx = fdhdx(1);
		dhdp = fdhdp(1);
		for ti = 1:601
			 dydp(:,:,ti) = dhdx(:,:,ti)*dxdp(:,:,ti) + dhdp(:,:,ti);
		end
	case 2
		dydp = zeros(1,9,601);
		dhdx = fdhdx(2);
		dhdp = fdhdp(2);
		for ti = 1:601
			 dydp(:,:,ti) = dhdx(:,:,ti)*dxdp(:,:,ti) + dhdp(:,:,ti);
		end
	case 3
		dydp = zeros(1,9,601);
		dhdx = fdhdx(3);
		dhdp = fdhdp(3);
		for ti = 1:601
			 dydp(:,:,ti) = dhdx(:,:,ti)*dxdp(:,:,ti) + dhdp(:,:,ti);
		end
	case 4
		dydp = zeros(1,9,601);
		dhdx = fdhdx(4);
		dhdp = fdhdp(4);
		for ti = 1:601
			 dydp(:,:,ti) = dhdx(:,:,ti)*dxdp(:,:,ti) + dhdp(:,:,ti);
		end
	case 5
		dydp = zeros(1,9,601);
		dhdx = fdhdx(5);
		dhdp = fdhdp(5);
		for ti = 1:601
			 dydp(:,:,ti) = dhdx(:,:,ti)*dxdp(:,:,ti) + dhdp(:,:,ti);
		end
end % end of switch/case exp

%%%%   HELPER FUNCTIONS %%%%

	function Hx = fdhdx(exp)
	% Calucates the partial derivative of the observaton function wrt the states
		switch exp
		case 1
				Hx = zeros(1,4,601);
				Hx(1,4,:) = 1;
		case 2
				Hx = zeros(1,4,601);
				Hx(1,4,:) = 1;
		case 3
				Hx = zeros(1,4,601);
				Hx(1,4,:) = 1;
		case 4
				Hx = zeros(1,4,601);
				Hx(1,4,:) = 1;
		case 5
				Hx = zeros(1,4,601);
				Hx(1,4,:) = 1;
		end  % end of switch
	end % end of fdhdp

	function Hp = fdhdp(exp)
	%Calculates the partial derivative of the objective wrt the parameters.
		switch exp
			case 1
				Hp = zeros(1,9,601);
			case 2
				Hp = zeros(1,9,601);
			case 3
				Hp = zeros(1,9,601);
			case 4
				Hp = zeros(1,9,601);
			case 5
				Hp = zeros(1,9,601);
		end  % end of switch
	end % end of fdhdp

end % end of main function

